---
output: 
  html_document:
    css: style.css
    highlight: textmate
---

# Planilla de Códigos

- [Stata](archivos/Planilla_Stata.do)
- [R](archivos/Planilla_R.R)
- [Python](archivos/Planilla_Python.py)
- [Manim (Python)](archivos/Planilla Manim.ipynb)
- [Latex - Papers](archivos/Planilla_Papers.zip)
- [Latex - Beamers](archivos/Planilla-Beamers.tex)

# Trabajos Universitarios

- [Mauricio, Diagnóstico de Crecimiento](archivos/Mauricio_Diagnostico_de_Crecimiento.pdf)
- [Efecto del Hacinamiento en el Desarrollo de los Niños](archivos/Hacinamiento.pdf)
- [Modelo CAPM en Chile 2010-2021](archivos/Capm.pdf)
- [Efecto de la Capacitación en la Productividad de las Empresas en 2017](archivos/Capacitaciones.pdf)

# Apuntes 

- [Econometría - Demostraciones](archivos/Demostraciones_Econometria.pdf) (En desarrollo con [Christian González](https://chrgonziba.github.io/))
- [Microeconomía - Modelos y Demostraciones](archivos/Microeconomía_modelos_demostraciones.pdf) (En desarrollo)
- [Macroeconomía - Modelos y Demostraciones](archivos/Macroeconomía_modelos_demostraciones.pdf) (En desarrollo)

# Ayudantías y Evaluaciones

- [Econometría I - Ayudantías](archivos/Ayudantias_econometria_I.pdf)
- [Microeconomía I - Ayudantías](archivos/Ayudantias_microeconomia_I.pdf)
- [Microeconomía I - Evaluaciones](archivos/Evaluaciones_microeconomia_I.pdf)
- [Introducción a las Finanzas - Ayudantía Solidaria](archivos/Ayudantia_Solidaria_Intro_a_Finanzas.pdf)
- [Finanzas I - Ayudantías](archivos/Pautas_Ayudantias_Finanzas I.pdf) (Desarrollado junto a Alejandro Lainez)
- [Finanzas I - Evaluaciones](archivos/Pautas_Evaluaciones_Finanzas_I.pdf) (Desarrollado junto a Juan Romagosa y Alejandro Lainez)
- [Introducción a las Finanzas - Ayudantías](archivos/Pautas_Ayudantias_Intro_a_Finanzas.pdf) (Desarrollado junto a Vicente Bavestrello y Rodrigo Fuentealba)
- [Introducción a las Finanzas - Evaluaciones](archivos/Pautas_Evaluaciones_Intro_a_Finanzas.pdf) (Desarrollado junto a Juan Romagosa, Vicente Bavestrello y Rodrigo Fuentealba)

